2025-01-29 @ 14:13:23 - [INFO] Linx Fast 2.0.py:69 (root/__init__) --> Inicializando a aplicação...
2025-01-29 @ 14:13:23 - [ERROR] Linx Fast 2.0.py:79 (root/__init__) --> Erro ao inicializar a aplicação: couldn't recognize data in image file "c:\Users\hamilton.santos\Desktop\Projects\Linx-Fast-2.0\assets/icons\logo.png"
2025-01-29 @ 14:13:27 - [INFO] Linx Fast 2.0.py:69 (root/__init__) --> Inicializando a aplicação...
2025-01-29 @ 14:13:27 - [ERROR] Linx Fast 2.0.py:79 (root/__init__) --> Erro ao inicializar a aplicação: couldn't recognize data in image file "c:\Users\hamilton.santos\Desktop\Projects\Linx-Fast-2.0\assets/icons\logo.png"
2025-01-29 @ 14:13:43 - [INFO] Linx Fast 2.0.py:69 (root/__init__) --> Inicializando a aplicação...
2025-01-29 @ 14:13:43 - [ERROR] Linx Fast 2.0.py:79 (root/__init__) --> Erro ao inicializar a aplicação: couldn't recognize data in image file "c:\Users\hamilton.santos\Desktop\Projects\Linx-Fast-2.0\assets/icons\logo.png"
2025-01-29 @ 14:14:03 - [INFO] Linx Fast 2.0.py:69 (root/__init__) --> Inicializando a aplicação...
2025-01-29 @ 14:14:03 - [ERROR] Linx Fast 2.0.py:77 (root/__init__) --> Erro ao inicializar a aplicação: couldn't recognize data in image file "c:\Users\hamilton.santos\Desktop\Projects\Linx-Fast-2.0\assets/icons\logo.png"
2025-01-29 @ 14:14:44 - [INFO] Linx Fast 2.0.py:69 (root/__init__) --> Inicializando a aplicação...
2025-01-29 @ 14:14:44 - [ERROR] Linx Fast 2.0.py:77 (root/__init__) --> Erro ao inicializar a aplicação: couldn't recognize data in image file "c:\Users\hamilton.santos\Desktop\Projects\Linx-Fast-2.0\assets/icons\logo.png"
2025-01-29 @ 14:15:31 - [INFO] Linx Fast 2.0.py:69 (root/__init__) --> Inicializando a aplicação...
2025-01-29 @ 14:15:31 - [ERROR] Linx Fast 2.0.py:77 (root/__init__) --> Erro ao inicializar a aplicação: couldn't recognize data in image file "c:\Users\hamilton.santos\Desktop\Projects\Linx-Fast-2.0\assets\icons\logo.png"
2025-01-29 @ 14:15:48 - [INFO] Linx Fast 2.0.py:69 (root/__init__) --> Inicializando a aplicação...
2025-01-29 @ 14:15:48 - [ERROR] Linx Fast 2.0.py:77 (root/__init__) --> Erro ao inicializar a aplicação: couldn't recognize data in image file "c:\Users\hamilton.santos\Desktop\Projects\Linx-Fast-2.0\assets/icons\logo.png"
2025-01-30 @ 10:59:10 - [INFO] Linx Fast 2.0.py:69 (root/__init__) --> Inicializando a aplicação...
2025-01-30 @ 10:59:10 - [ERROR] Linx Fast 2.0.py:77 (root/__init__) --> Erro ao inicializar a aplicação: couldn't recognize data in image file "c:\Users\hamilton.santos\Desktop\Projects\Linx-Fast-2.0\assets/icons\logo.png"
2025-01-30 @ 11:02:16 - [INFO] Linx Fast 2.0.py:69 (root/__init__) --> Inicializando a aplicação...
2025-01-30 @ 11:02:16 - [ERROR] Linx Fast 2.0.py:77 (root/__init__) --> Erro ao inicializar a aplicação: couldn't recognize data in image file "c:\Users\hamilton.santos\Desktop\Projects\Linx-Fast-2.0\assets/icons\logo.png"
2025-01-30 @ 11:02:30 - [INFO] Linx Fast 2.0.py:69 (root/__init__) --> Inicializando a aplicação...
2025-01-30 @ 11:02:31 - [ERROR] Linx Fast 2.0.py:77 (root/__init__) --> Erro ao inicializar a aplicação: couldn't recognize data in image file "c:\Users\hamilton.santos\Desktop\Projects\Linx-Fast-2.0\assets\icons\logo.png"
2025-01-30 @ 11:07:31 - [INFO] Linx Fast 2.0.py:69 (root/__init__) --> Inicializando a aplicação...
2025-01-30 @ 11:07:32 - [ERROR] Linx Fast 2.0.py:77 (root/__init__) --> Erro ao inicializar a aplicação: couldn't recognize data in image file "c:\Users\hamilton.santos\Desktop\Projects\Linx-Fast-2.0\assets\icons\logo.png"
2025-01-30 @ 11:09:24 - [INFO] Linx Fast 2.0.py:69 (root/__init__) --> Inicializando a aplicação...
2025-01-30 @ 11:09:24 - [ERROR] Linx Fast 2.0.py:83 (root/__init__) --> Erro ao carregar a imagem: couldn't recognize data in image file "c:\Users\hamilton.santos\Desktop\Projects\Linx-Fast-2.0\assets\icons\logo.png"
2025-01-30 @ 11:10:10 - [INFO] Linx Fast 2.0.py:69 (root/__init__) --> Inicializando a aplicação...
2025-01-30 @ 11:10:10 - [ERROR] Linx Fast 2.0.py:83 (root/__init__) --> Erro ao carregar a imagem: couldn't recognize data in image file "c:\Users\hamilton.santos\Desktop\Projects\Linx-Fast-2.0\assets\icons\logo.png"
2025-01-30 @ 11:11:26 - [INFO] Linx Fast 2.0.py:69 (root/__init__) --> Inicializando a aplicação...
2025-01-30 @ 11:11:26 - [ERROR] Linx Fast 2.0.py:83 (root/__init__) --> Erro ao carregar a imagem: couldn't recognize data in image file "c:\Users\hamilton.santos\Desktop\Projects\Linx-Fast-2.0\assets\icons\logo.png"
2025-01-30 @ 11:12:36 - [INFO] Linx Fast 2.0.py:69 (root/__init__) --> Inicializando a aplicação...
2025-01-30 @ 11:12:36 - [ERROR] Linx Fast 2.0.py:77 (root/__init__) --> Erro ao inicializar a aplicação: couldn't recognize data in image file "c:\Users\hamilton.santos\Desktop\Projects\Linx-Fast-2.0\assets\icons\logo.png"
2025-01-30 @ 11:13:16 - [INFO] Linx Fast 2.0.py:69 (root/__init__) --> Inicializando a aplicação...
2025-01-30 @ 11:13:16 - [ERROR] Linx Fast 2.0.py:77 (root/__init__) --> Erro ao inicializar a aplicação: couldn't open "c:\Users\hamilton.santos\Desktop\Projects\Linx-Fast-2.0\assets\icons\pyLauncher.png": no such file or directory
2025-01-30 @ 11:14:36 - [INFO] Linx Fast 2.0.py:69 (root/__init__) --> Inicializando a aplicação...
2025-01-30 @ 11:14:37 - [ERROR] Linx Fast 2.0.py:77 (root/__init__) --> Erro ao inicializar a aplicação: couldn't recognize data in image file "c:\Users\hamilton.santos\Desktop\Projects\Linx-Fast-2.0\assets\icons\logo.png"
2025-01-30 @ 11:14:46 - [INFO] Linx Fast 2.0.py:69 (root/__init__) --> Inicializando a aplicação...
2025-01-30 @ 11:15:16 - [INFO] Linx Fast 2.0.py:69 (root/__init__) --> Inicializando a aplicação...
2025-01-30 @ 11:15:27 - [INFO] Linx Fast 2.0.py:69 (root/__init__) --> Inicializando a aplicação...
2025-01-30 @ 11:15:27 - [ERROR] Linx Fast 2.0.py:77 (root/__init__) --> Erro ao inicializar a aplicação: couldn't recognize data in image file "c:\Users\hamilton.santos\Desktop\Projects\Linx-Fast-2.0\assets\icons\logo.png"
2025-01-30 @ 11:21:20 - [INFO] Linx Fast 2.0.py:69 (root/__init__) --> Inicializando a aplicação...
2025-01-30 @ 11:21:20 - [ERROR] Linx Fast 2.0.py:80 (root/__init__) --> Erro ao inicializar a aplicação: couldn't recognize data in image file "c:\Users\hamilton.santos\Desktop\Projects\Linx-Fast-2.0\assets\icons\logo.png"
2025-01-30 @ 11:23:20 - [INFO] Linx Fast 2.0.py:69 (root/__init__) --> Inicializando a aplicação...
2025-01-30 @ 11:23:20 - [ERROR] Linx Fast 2.0.py:81 (root/__init__) --> Erro ao inicializar a aplicação: couldn't recognize data in image file "c:\Users\hamilton.santos\Desktop\Projects\Linx-Fast-2.0\assets\icons\logo.png"
2025-01-30 @ 11:24:14 - [INFO] Linx Fast 2.0.py:69 (root/__init__) --> Inicializando a aplicação...
2025-01-30 @ 11:24:14 - [ERROR] Linx Fast 2.0.py:81 (root/__init__) --> Erro ao inicializar a aplicação: couldn't recognize data in image file "c:\Users\hamilton.santos\Desktop\Projects\Linx-Fast-2.0\assets\icons\logo.png"
2025-01-30 @ 11:25:51 - [INFO] Linx Fast 2.0.py:69 (root/__init__) --> Inicializando a aplicação...
2025-01-30 @ 11:25:51 - [ERROR] Linx Fast 2.0.py:81 (root/__init__) --> Erro ao inicializar a aplicação: 'config' is not implemented for CTk widgets. For consistency, always use 'configure' instead.
2025-01-30 @ 11:26:30 - [INFO] Linx Fast 2.0.py:69 (root/__init__) --> Inicializando a aplicação...
